@startuml overall_databaserm 
title Zjednodušený ER diagram

' Skrytí zbytečných ikon a prázdných částí pro čistší vzhled
hide circle
hide empty members
skinparam linetype ortho

' Kompaktní mezery ideální pro vložení do textu
skinparam nodesep 40
skinparam ranksep 50

' Definice entit pouze s klíčovými byznys atributy
entity "teams" as teams {
  * team_name (PK)
}

entity "contributors_teams" as ct {
  * team (FK)
  * contributor_id (FK)
}

entity "contributors" as contributors {
  * github_id (PK)
  --
  github_name
}

entity "issues" as issues {
  * repository (PK)
  * issue_id (PK)
  --
  is_pr
  current_state
}

entity "issue_labels_history" as labels {
  * issue_id (FK)
  --
  label_name
  action
  is_pr
}

entity "issue_event_history" as events {
  * issue_id (FK)
  --
  event_type
  is_pr
}

entity "file_activity" as files {
  * issue_id (FK)
  --
  file_path
}

' ---- Vazby a layout ----
teams ||-up-o{ ct
contributors ||-left-o{ ct

contributors ||-down-o{ issues : " autor"

issues ||-down-o{ events
issues ||-down-o{ labels
issues ||-down-o{ files

@enduml